class ParamSource:
    def __init__(self):
        pass
    def get_markers(self):  
        return ['.',',','o','v','^','<','>','1','2','3','4','8','s','p','P','*','h','H','+','x','X','D','d','|','_']
    def get_lines(self):
        return ['-',':','--','-.','']
    
    def get_cmaps(self):
        return  ['Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'binary', 'binary_r', 'bone', 'bone_r', 'brg', 'brg_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'cubehelix', 'cubehelix_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r', 'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r', 'gist_yarg', 'gist_yarg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'hot', 'hot_r', 'hsv', 'hsv_r', 'inferno', 'inferno_r', 'jet', 'jet_r', 'magma', 'magma_r', 'nipy_spectral', 'nipy_spectral_r', 'ocean', 'ocean_r', 'pink', 'pink_r', 'plasma', 'plasma_r', 'prism', 'prism_r', 'rainbow', 'rainbow_r', 'seismic', 'seismic_r', 'spring', 'spring_r', 'summer', 'summer_r', 'tab10', 'tab10_r', 'tab20', 'tab20_r', 'tab20b', 'tab20b_r', 'tab20c', 'tab20c_r', 'terrain', 'terrain_r', 'turbo', 'turbo_r', 'twilight', 'twilight_r', 'twilight_shifted', 'twilight_shifted_r', 'viridis', 'viridis_r', 'winter', 'winter_r']
    
    def get_colors(self):    
        return ['black','k','dimgray','dimgrey','grey','gray','darkgrey','darkgray','silver','lightgray','lightgrey','gainsboro','whitesmoke','white','w','snow','rosybrown','lightcoral','indianred','brown','firebrick','maroon','darkred','red','r','mistyrose','salmon','tomato','darksalmon','coral','orangered','lightsalmon','sienna','seashell','chocolate','saddlebrown','sandybrown','peachpuff','peru','linen','bisque','darkorange','burlywood','antiquewhite','tan','navajowhite','blanckedalmond','papayawhip','moccasin','orange','wheat','oldlace','floralwhite','darkgoldenrod','goldenrod','cornsilk','gold','lemonchiffon','khaki','palegoldenrod','darkkhaki','ivory','beige','lightyellow','lightgoldenrodyellow','olive','y','yellow','olivedrab','yellowgreen','darkolivegreen','greenyellow','charteuse','lawngreen','sage','lightsage','darksage','honeydew','darkseagreen','palegreen','lightgreen','forestgreen','limegreen','darkgreen','green','g','lime','seagreen','mediumseagreen','springgreen','mintcream','mediumspringgreen','mediumaquamarine','aquamarine','turquoise','lightseagreen','mediumturquoise','azure','lightcyan','paleturquoise','darkslategray','darkslategrey','teal','darkcyan','c','cyan','aqua','darkturquoise','cadetblue','powderblue','lightblue','deepskyblue','skyblue','lightskyblue','deepskyblue','skyblue','lightskyblue','steelblue','aliceblue','dodgerblue','lightslategrey','lightslategray','slategray','slategrey','lightsteelblue','cornglowerblue','royalblue','ghostwhite','lavender','midnightblue','navy','darkblue','mediumblue','blue','b','slateblue','darkslateblue','mediumslateblue','mediumpurple','blueviolet','indigo','darkorchid','darkviolet','mediumorchid','thistle','plum','violet','purple','darkmagenta','m','fuchsia','magenta','orchid','mediumvioletred','deeppink','hotpink','lavenderblush','palevioletred','crimson','pink','lightpink']
   
    def get_hatchs(self):
        return ['','/','\\','|','-','+','x','o','O','.','*','//','\\\\','||','--','++','xx','oo','OO','..','**','/o','\\|','|*','-\\','+o','x*','o-','O|','O.','*-']
    def get_fonts(self):
        return ['cmr10', 'DejaVu Sans', 'STIXGeneral', 'STIXGeneral', 'STIXSizeTwoSym', 'DejaVu Sans', 'STIXSizeFiveSym', 'STIXSizeThreeSym', 'cmtt10', 'DejaVu Sans Mono', 'DejaVu Serif Display', 'STIXGeneral', 'STIXNonUnicode', 'DejaVu Sans Display', 'STIXSizeOneSym', 'DejaVu Serif', 'STIXSizeFourSym', 'cmb10', 'STIXNonUnicode', 'STIXSizeTwoSym', 'DejaVu Sans', 'cmmi10', 'DejaVu Sans Mono', 'DejaVu Serif', 'STIXNonUnicode', 'cmss10', 'DejaVu Sans Mono', 'DejaVu Sans Mono', 'DejaVu Serif', 'STIXNonUnicode', 'cmex10', 'STIXSizeThreeSym', 'STIXGeneral', 'cmsy10', 'STIXSizeOneSym', 'DejaVu Sans', 'STIXSizeFourSym', 'DejaVu Serif', 'Times New Roman', 'Microsoft YaHei', 'Myanmar Text', 'Candara', 'Segoe UI', 'Cambria', 'Segoe UI Emoji', 'Candara', 'Cambria', 'Leelawadee UI', 'Wingdings', 'Corbel', 'Gadugi', 'Segoe UI', 'Nirmala UI', 'Candara', 'Arial', 'Lucida Console', 'Microsoft Tai Le', 'Comic Sans MS', 'Microsoft Tai Le', 'DengXian', 'Consolas', 'Segoe MDL2 Assets', 'Microsoft Himalaya', 'Tahoma', 'Sitka Small', 'Segoe UI Historic', 'Marlett', 'Microsoft YaHei', 'Georgia', 'Corbel', 'Nirmala UI', 'Segoe Script', 'Candara', 'Yu Gothic', 'Trebuchet MS', 'Microsoft New Tai Lue', 'Calibri', 'Calibri', 'Calibri', 'Corbel', 'Segoe UI', 'Symbol', 'Trebuchet MS', 'Trebuchet MS', 'Palatino Linotype', 'Times New Roman', 'Javanese Text', 'Arial', 'Microsoft JhengHei', 'Courier New', 'Microsoft Yi Baiti', 'Arial', 'Georgia', 'Consolas', 'Franklin Gothic Medium', 'Segoe UI', 'Cambria', 'Consolas', 'MT Extra', 'MingLiU-ExtB', 'Arial', 'Bahnschrift', 'Malgun Gothic', 'Segoe UI', 'Gabriola', 'Lucida Sans Unicode', 'MV Boli', 'Segoe UI', 'Microsoft YaHei', 'Ink Free', 'Webdings', 'Leelawadee UI', 'Leelawadee UI', 'Sylfaen', 'Consolas', 'Malgun Gothic', 'Malgun Gothic', 'Segoe Script', 'Segoe UI', 'Constantia', 'Segoe UI', 'Ebrima', 'Nirmala UI', 'Segoe UI', 'Candara', 'Verdana', 'Tahoma', 'Myanmar Text', 'Comic Sans MS', 'Calibri', 'Georgia', 'Calibri', 'Times New Roman', 'Mongolian Baiti', 'Segoe Print', 'Cambria', 'Palatino Linotype', 'Corbel', 'Verdana', 'Sitka Small', 'Courier New', 'Segoe UI', 'Microsoft JhengHei', 'Comic Sans MS', 'Sitka Small', 'Palatino Linotype', 'Palatino Linotype', 'Trebuchet MS', 'DengXian', 'Verdana', 'HoloLens MDL2 Assets', 'Sitka Small', 'Segoe Print', 'Microsoft New Tai Lue', 'FangSong', 'Courier New', 'Microsoft PhagsPa', 'SimHei', 'Segoe UI', 'Comic Sans MS', 'DengXian', 'Times New Roman', 'Segoe UI', 'Corbel', 'Courier New', 'Segoe UI Symbol', 'Franklin Gothic Medium', 'Microsoft PhagsPa', 'Calibri', 'DejaVu Math TeX Gyre', 'Yu Gothic', 'Microsoft Sans Serif', 'KaiTi', 'Yu Gothic', 'Yu Gothic', 'Corbel', 'SimSun', 'Georgia', 'Arial', 'Candara', 'SimSun-ExtB', 'Verdana', 'Gadugi', 'Impact', 'Microsoft JhengHei', 'MS Gothic', 'Ebrima']
       
       